<?php

/**
 * Configuration des routes pour l'authentification et les redirections 301.
 *
 * Utilisé par public/index.php pour :
 * - Middleware global : chemins publics vs protégés
 * - registerRedirects() : anciennes URL vers nouveau schéma de nommage
 */

return [
    // Chemins exacts accessibles sans authentification
    'exact_public_paths' => [
        '/',
        '/login',
        '/logout',
        '/ping',
        '/favicon.ico',
    ],

    // Préfixes de chemins accessibles sans authentification (strpos === 0)
    'public_paths' => [
        '/aquaponie',
        '/aquaponie-alt',
        '/aquaponie-test',
        '/aquaponie-alt-test',
        '/aquamobile',
        '/aquamobile-alt',
        '/aquamobile-test',
        '/aquamobile-alt-test',
        '/aquaponie-description',
        '/meteo-description',
        '/serre-description',
        '/meteo',
        '/serre',
        '/gallery',
        '/post-data',
        '/post-data-test',
        '/post-data3',
        '/post-data3-test',
        '/post-data-s3-test',
        '/heartbeat',
        '/heartbeat-test',
        '/heartbeat3',
        '/heartbeat3-test',
        '/heartbeat-s3-test',
        '/api/realtime',
        '/api/realtime-test',
        '/api/realtime3',
        '/api/realtime3-test',
        '/api/realtime-s3-test',
        '/api/health',
        '/api/health-test',
        '/api/outputs/state',
        '/api/outputs-test/state',
        '/api/outputs3/state',
        '/api/outputs3-test/state',
        '/api/outputs-s3-test/state',
        '/ffp3/api/outputs/state',
        '/ffp3/api/outputs-test/state',
        '/ffp3/api/outputs3/state',
        '/ffp3/api/outputs3-test/state',
        '/ffp3/api/outputs-s3-test/state',
        '/ffp3/ota/',
        '/ota/',
        '/assets/',
        '/msp1gallery/',
        '/n3ppgallery/',
        '/ffp3gallery/',
        '/ffp3/ffp3gallery/',
        '/msp1gallery/uploadphotoserver-outputs-action.php',
        '/msp1/msp1gallery/uploadphotoserver-outputs-action.php',
        '/n3ppgallery/uploadphotoserver-outputs-action.php',
        '/n3pp/n3ppgallery/uploadphotoserver-outputs-action.php',
        '/ffp3gallery/uploadphotoserver-outputs-action.php',
        '/ffp3/ffp3gallery/uploadphotoserver-outputs-action.php',
        '/msp1gallery/post-uploadphotoserver-version.php',
        '/msp1/msp1gallery/post-uploadphotoserver-version.php',
        '/n3ppgallery/post-uploadphotoserver-version.php',
        '/n3pp/n3ppgallery/post-uploadphotoserver-version.php',
        '/ffp3gallery/post-uploadphotoserver-version.php',
        '/ffp3/ffp3gallery/post-uploadphotoserver-version.php',
        '/gallery/msp1/api/outputs/state',
        '/gallery/n3pp/api/outputs/state',
        '/gallery/ffp3/api/outputs/state',
        '/gallery/msp1/api/firmware/version',
        '/gallery/n3pp/api/firmware/version',
        '/gallery/ffp3/api/firmware/version',
        '/msp1/msp1datas/',
        '/msp1/api/realtime/',
        '/msp1/api/outputs/state',
        '/msp1/msp1control/msp1-outputs-action.php',
        '/msp1-test/msp1datas/',
        '/msp1-test/api/realtime/',
        '/msp1-test/api/outputs/state',
        '/msp1-test/msp1control/msp1-outputs-action.php',
        '/n3pp/n3ppdatas/',
        '/n3pp/api/realtime/',
        '/n3pp/api/outputs/state',
        '/n3pp/n3ppcontrol/n3pp-outputs-action.php',
        '/n3pp-test/n3ppdatas/',
        '/n3pp-test/api/realtime/',
        '/n3pp-test/api/outputs/state',
        '/n3pp-test/n3ppcontrol/n3pp-outputs-action.php',
        '/n3ppdatas/',
        '/msp1datas/',
        '/ffp3control/',  // Legacy : getOutputsState
        '/pgl/',
    ],

    // Préfixes de chemins protégés (authentification requise)
    'protected_paths' => [
        '/dashboard',
        '/dashboard-test',
        '/dashboard-s3-test',
        '/aquaponie-control',
        '/aquaponie-control-test',
        '/aquamobile-control',
        '/aquamobile-control-test',
        '/aquamobile-control-s3-test',
        '/supervision',
        '/export-data',
        '/tide-stats',
        '/tide-stats-test',
        '/tide-stats-s3-test',
        '/export-data-s3-test',
        '/meteo-control',
        '/serre-control',
        '/msp1-test/msp1control',
        '/n3pp-test/n3ppcontrol',
        '/gallery/msp1/control',
        '/gallery/n3pp/control',
        '/gallery/ffp3/control',
        '/gallery/msp1/api/outputs/toggle',
        '/gallery/n3pp/api/outputs/toggle',
        '/gallery/ffp3/api/outputs/toggle',
        '/gallery/msp1/api/outputs/parameters',
        '/gallery/n3pp/api/outputs/parameters',
        '/gallery/ffp3/api/outputs/parameters',
        '/gallery/msp1/api/outputs/notification-policy',
        '/gallery/n3pp/api/outputs/notification-policy',
        '/gallery/ffp3/api/outputs/notification-policy',
        '/msp1/api/outputs/toggle',
        '/msp1/api/outputs/parameters',
        '/msp1/api/outputs/notification-policy',
        '/msp1-test/api/outputs/toggle',
        '/msp1-test/api/outputs/parameters',
        '/msp1-test/api/outputs/notification-policy',
        '/n3pp/api/outputs/toggle',
        '/n3pp/api/outputs/parameters',
        '/n3pp/api/outputs/notification-policy',
        '/n3pp-test/api/outputs/toggle',
        '/n3pp-test/api/outputs/parameters',
        '/n3pp-test/api/outputs/notification-policy',
        '/admin/',
    ],

    // Rôle minimum requis par préfixe de chemin (hiérarchie : reader < operator < admin)
    'role_requirements' => [
        'admin' => [
            '/admin/users',
            // Page de supervision et actions de maintenance qu'elle expose :
            // réservées aux administrateurs (vidage caches, tri galeries, script
            // de déploiement). NB : le matching (RoleAccessService::pathStartsWith)
            // exige une frontière `/` ou fin après le préfixe → chaque variante
            // d'environnement doit être listée explicitement (comme pour reader).
            '/supervision',
            '/admin/clear-cache',
            '/admin/clear-cache-test',
            '/admin/clear-cache3',
            '/admin/clear-cache3-test',
            '/admin/clear-cache-s3-test',
            '/admin/api/gallery/auto-sort-all',
            '/admin/deploy-script',
            '/admin/hmac-audit',
            '/admin/api/hmac-audit/toggle',
        ],
        'reader' => [
            '/dashboard',
            '/dashboard-test',
            '/dashboard3',
            '/dashboard3-test',
            '/dashboard-s3-test',
            '/tide-stats',
            '/tide-stats-test',
            '/tide-stats3',
            '/tide-stats3-test',
            '/tide-stats-s3-test',
            '/export-data',
            '/export-data-test',
            '/export-data3',
            '/export-data3-test',
            '/export-data-s3-test',
        ],
    ],

    // Whitelist des assets servis par registerAssetRoute()
    'asset_js' => [
        'back-to-top.js', 'balance-reveal.js', 'breakpoints.min.js', 'browser.min.js',
        'chart-helpers.js', 'chart-updater-generic.js', 'chart-updater.js', 'chartjs-theme.js',
        'control-actions.js', 'control-auto-save.js', 'control-sync.js', 'control-values-updater.js', 'gallery-lightbox.js', 'notification-policy.js',
        'confirm-modal.js', 'admin-users.js',
        'highstock.js', 'exporting.js', 'export-data.js', 'accessibility.js',
        'highcharts-defaults.js', 'highcharts-theme.js', 'n3-stock-chart-layout.js', 'n3-stock-chart-bootstrap.js', 'aquaponie-chart-layout.js', 'aquaponie-tide-markers.js', 'jquery.min.js', 'jquery.scrollex.min.js',
        'jquery.scrolly.min.js', 'main.js', 'page-nav-toggles.js', 'period-nav.js', 'pwa-init.js',
        'realtime-updater.js', 'scroll-progress.js', 'scroll-reveal.js', 'stats-updater.js',
        'theme-toggle.js', 'toast-notifications.js', 'util.js',
        'moment.min.js', 'moment-timezone-with-data.min.js',
    ],
    'asset_css' => [
        'aquaponie.css', 'aquaponie-description-styles.css', 'common-data.css', 'control-styles.css',
        'fontawesome.min.css',
        'gallery-styles.css', 'home-styles.css', 'login-styles.css', 'main.css', 'admin-users.css',
        'module-description-styles.css', 'msp1-sheet-styles.css', 'noscript.css', 'realtime-styles.css', 'supervision-styles.css',
        'theme-variables.css', 'timelapse-styles.css',
    ],
    'asset_icons' => [
        'icon-72.png', 'icon-96.png', 'icon-128.png', 'icon-144.png', 'icon-152.png',
        'icon-192.png', 'icon-384.png', 'icon-512.png', 'favicon-n3-orange.png',
    ],
    'asset_webfonts' => [
        'fa-solid-900.woff2', 'fa-regular-400.woff2', 'fa-brands-400.woff2',
    ],

    // Redirections 301 : [ancienne_url, nouvelle_url, méthodes]
    // Méthodes : ['GET'] ou ['GET', 'POST']
    'redirects_301' => [
        ['/control', '/aquaponie-control', ['GET']],
        ['/control-test', '/aquaponie-control-test', ['GET']],
        ['/control3', '/aquamobile-control', ['GET']],
        ['/control3-test', '/aquamobile-control-test', ['GET']],
        ['/aquaponie3', '/aquamobile', ['GET', 'POST']],
        ['/aquaponie3-test', '/aquamobile-test', ['GET', 'POST']],
        ['/aquaponie-alt3', '/aquamobile-alt', ['GET', 'POST']],
        ['/aquaponie-alt3-test', '/aquamobile-alt-test', ['GET', 'POST']],
        ['/ffp3-data', '/aquaponie', ['GET', 'POST']],
        ['/heartbeat.php', '/heartbeat', ['POST']],
        ['/heartbeat-test.php', '/heartbeat-test', ['POST']],
    ],
];
